# Text Representation

## Student Information

**Name:** abdullah hejji alnuwaysir  
**ID:** 2240005501

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [3]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) # returns sparce matrix

In [4]:
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [5]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [6]:
# Sample text data (replace with your own documents)

doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [7]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [8]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

                                        Data is the oil of the digital economy  Data is a new oil
Data is the oil of the digital economy                                1.000000           0.327871
Data is a new oil                                                     0.327871           1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embeddings. These models learn numerical vector representations of words from their surrounding context.

Word2Vec utilizes two architectures:
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**

<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">

We will use the **Simpsons script dataset** provided with this lab for the required Skip-Gram experiment.

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [9]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

sentences = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?"
]

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(sentences)

cosine_matrix = cosine_similarity(tfidf_matrix)

cosine_df = pd.DataFrame(
    cosine_matrix,
    index=[f"Sentence {i}" for i in range(1, 5)],
    columns=[f"Sentence {i}" for i in range(1, 5)]
)

print("Cosine Similarity Matrix:")
display(cosine_df.round(6))

print("\nMost similar pair(s):")
for i in range(len(sentences)):
    for j in range(i + 1, len(sentences)):
        if cosine_matrix[i, j] == cosine_matrix[np.triu_indices(len(sentences), 1)].max():
            print(f"Sentence {i+1} and Sentence {j+1}: {cosine_matrix[i, j]:.6f}")

Cosine Similarity Matrix:

            Sentence 1  Sentence 2  Sentence 3  Sentence 4
Sentence 1    1.000000    0.646926    0.307772    1.000000
Sentence 2    0.646926    1.000000    0.225240    0.646926
Sentence 3    0.307772    0.225240    1.000000    0.307772
Sentence 4    1.000000    0.646926    0.307772    1.000000

Most similar pair(s):
Sentence 1 and Sentence 4: 1.000000

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [11]:
sentences_tfidf = [
    "data science is one of the most important fields of science",
    "this is one of the best data science courses",
    "data scientists analyze data"
]

tfidf_vectorizer_2 = TfidfVectorizer()
tfidf_matrix_2 = tfidf_vectorizer_2.fit_transform(sentences_tfidf)
terms = tfidf_vectorizer_2.get_feature_names_out()

tfidf_df = pd.DataFrame(
    tfidf_matrix_2.toarray(),
    columns=terms,
    index=[f"Sentence {i}" for i in range(1, 4)]
)

print("TF-IDF values:")
display(tfidf_df.round(6))

print("\nTop important words in each sentence (highest TF-IDF):")
for i, row in enumerate(tfidf_matrix_2.toarray()):
    top_indices = np.argsort(row)[::-1]
    top_words = [(terms[j], round(row[j], 6)) for j in top_indices if row[j] > 0][:5]
    print(f"Sentence {i+1}: {top_words}")

TF-IDF values:

             analyze      best   courses  ...  scientists       the      this
Sentence 1  0.000000  0.000000  0.000000  ...    0.000000  0.244049  0.000000
Sentence 2  0.000000  0.400294  0.400294  ...    0.000000  0.304434  0.400294
Sentence 3  0.542701  0.000000  0.000000  ...    0.542701  0.000000  0.000000

[3 rows x 14 columns]

Top important words in each sentence (highest TF-IDF):
Sentence 1: [('of', np.float64(0.488098)), ('science', np.float64(0.488098)), ('important', np.float64(0.320895)), ('fields', np.float64(0.320895)), ('most', np.float64(0.320895))]
Sentence 2: [('this', np.float64(0.400294)), ('best', np.float64(0.400294)), ('courses', np.float64(0.400294)), ('one', np.float64(0.304434)), ('science', np.float64(0.304434))]
Sentence 3: [('data', np.float64(0.641055)), ('scientists', np.float64(0.542701)), ('analyze', np.float64(0.542701))]

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [12]:
import os
import re
import pandas as pd
import gensim

# Locate the provided Simpsons dataset in common notebook locations.
possible_paths = [
    "simpsons_script_lines.csv",
    "/content/simpsons_script_lines.csv",
    "/mnt/data/simpsons_script_lines.csv"
]

dataset_path = next((p for p in possible_paths if os.path.exists(p)), None)
if dataset_path is None:
    raise FileNotFoundError(
        "simpsons_script_lines.csv was not found. Place the CSV file in the same folder as this notebook."
    )

simpsons_df = pd.read_csv(dataset_path)
simpsons_df["spoken_words"] = simpsons_df["spoken_words"].fillna("")

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

simpsons_df["clean_text"] = simpsons_df["spoken_words"].apply(clean_text)

# Tokenization for Word2Vec after preprocessing.
tokens = [
    re.findall(r"[a-z]+", text)
    for text in simpsons_df["clean_text"]
]
tokens = [sentence_tokens for sentence_tokens in tokens if sentence_tokens]

print("Dataset shape:", simpsons_df.shape)
display(simpsons_df[["spoken_words", "clean_text"]].head())

# Required Skip-Gram Word2Vec model.
Skip_gram_model = gensim.models.Word2Vec(
    tokens,
    min_count=1,
    vector_size=100,
    window=5,
    sg=1,
    seed=42,
    workers=4
)

print("\nNumber of tokenized lines:", len(tokens))
print("Vocabulary size:", len(Skip_gram_model.wv))

Dataset shape: (158314, 3)

                                        spoken_words                                         clean_text
0  No, actually, it was a little of both. Sometim...  no actually it was a little of both sometimes ...
1                             Where's Mr. Bergstrom?                              where's mr bergstrom?
2  I don't know. Although I'd sure like to talk t...  i don't know although i'd sure like to talk to...
3                         That life is worth living.                          that life is worth living
4  The polls will be open from now until the end ...  the polls will be open from now until the end ...

Number of tokenized lines: 131817
Vocabulary size: 43784

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [13]:
print("Words similar to 'homer':")
display(pd.DataFrame(
    Skip_gram_model.wv.most_similar("homer", topn=10),
    columns=["word", "similarity"]
).round(6))

print("Words similar to 'marge':")
display(pd.DataFrame(
    Skip_gram_model.wv.most_similar("marge", topn=10),
    columns=["word", "similarity"]
).round(6))

print("Words similar to 'bart':")
display(pd.DataFrame(
    Skip_gram_model.wv.most_similar("bart", topn=10),
    columns=["word", "similarity"]
).round(6))

Words similar to 'homer':

          word  similarity
0          abe    0.872077
1        marge    0.862644
2  bartholomew    0.829927
3       grampa    0.829742
4      colonel    0.827093
5        mindy    0.824436
6        eliza    0.822430
7    carefully    0.815077
8         bart    0.814402
9       barney    0.809725

Words similar to 'marge':

         word  similarity
0       homer    0.862644
1         abe    0.856509
2     sweetie    0.836613
3  sweetheart    0.830297
4       honey    0.822374
5        edna    0.820706
6       becky    0.818111
7     lurleen    0.813620
8        lisa    0.812080
9   carefully    0.810665

Words similar to 'bart':

       word  similarity
0  milhouse    0.867239
1      lisa    0.848216
2       abe    0.834677
3     eliza    0.829485
4    laddie    0.827846
5   jessica    0.824130
6       apu    0.823323
7   allison    0.815294
8     homer    0.814402
9    grampa    0.814352

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [14]:
groups = [
    ["jimbo", "milhouse", "kearney"],
    ["nelson", "bart", "milhouse"],
    ["homer", "patty", "selma"]
]

for words in groups:
    odd_word = Skip_gram_model.wv.doesnt_match(words)
    print(f"{words} -> odd word: {odd_word}")

['jimbo', 'milhouse', 'kearney'] -> odd word: milhouse
['nelson', 'bart', 'milhouse'] -> odd word: nelson
['homer', 'patty', 'selma'] -> odd word: homer

## Conclusion

TF-IDF converts text into weighted numerical features, while cosine similarity measures the similarity between text vectors. The Skip-Gram Word2Vec model learns word embeddings from the Simpsons dialogue and can then be used to find similar words and identify an odd word from a group.